### ISSUE TITLE
DirectX 11?

### ISSUE THREAD

**Issue by gesior** [edubart/otclient#669] opened 2015-06-26 21:51 UTC
In cmake I found something like 'DX11' 'not found'.

1. Are you planning to add DirectX 11 to otclient?
2. Is there a way to compile it with DirectX 11?

and final question..
Is (will?) DX11 faster then DX9 for so simple game?

**Comment by iryont** [comment] 2015-06-27 07:02
I'm afraid we do not have any of those painters (neither DirectX 11 or DirectX 9). However, there is cmake file to look for DirectX, but it is not used in the sources themselves. At the moment there are no plans to add it whatsoever.

**Comment by gesior** [comment] 2015-06-27 08:23
So how do I compile it with DX9? (on windows)
https://github.com/edubart/otclient/wiki/Compiling-on-Windows#dx9-support-layer

**Comment by iryont** [comment] 2015-06-27 08:26
You need to use the ANGLE project:
https://code.google.com/p/angleproject/

**Comment by gesior** [comment] 2015-06-27 08:30
I did not install anything. I changed it with some tutorial from otland. Compiled. Now in my client I got only option DX9. Is it fake or it really compiled with DX9?

Number of frames per second is diffrent, on my super fast PC (4x4.0GHz, GF 980 GTX 4GB) I got more frames with opengl (2000 with DX9, ~2400 with opengl), but my friend on laptop got more frames with DX9 (130 DX9, 100 opengl).

**Comment by iryont** [comment] 2015-06-27 08:32
Most likely it is :) If the application won't start without libGLESv2.dll then it is.

**Comment by gesior** [comment] 2015-06-27 08:36
I got that file. All was described on otland. "Download 2x .dll, set something in cmake config, rebuild" and now I got DX9 in game options. So is it DX9 or just fake? And if it's can anyone tell me how to compile it with DX 11 (maybe its already DX 11?)

In my makefile I got:

//Use DX9 support
DIRECTX:BOOL=OFF
//Path to a file.
DirectX_D3D11_INCLUDE_DIR:PATH=DirectX_D3D11_INCLUDE_DIR-NOTFOUND
//Path to a library.
DirectX_D3D11_LIBRARY:FILEPATH=C:/Windows/System32/d3d11.dll
//Path to a library.
DirectX_D3DCOMPILER_LIBRARY:FILEPATH=DirectX_D3DCOMPILER_LIBRARY-NOTFOUND
//Path to a library.
DirectX_D3DX11_LIBRARY:FILEPATH=DirectX_D3DX11_LIBRARY-NOTFOUND
//Path to a library.
DirectX_D3DX9_LIBRARY:FILEPATH=DirectX_D3DX9_LIBRARY-NOTFOUND

**Comment by iryont** [comment] 2015-06-27 10:59
If you want to use ANGLE for DirectX 11 you need to download correct libraries (ANGLE is available for DirectX 9.0c and DirectX 11) as well as you need to use valid HLSL compiler (library).

Anyway, I'm closing this issue since it's not a bug, but you are free to continue the discussion.

**Closed by iryont** 2015-06-27 10:59 UTC

**Comment by Anastaciaa** [comment] 2015-07-01 17:37
There was actually alot of threads related to directx support but no one get this working even edubart or summ. There is simply no support for it. Angle libraries has been tested aswell without result and i think Iryont should try this before giving an answer.

**Comment by iryont** [comment] 2015-07-01 17:42
Oh, believe me I did. ANGLE project for DirectX 9.0c works just fine since I do use it on my server. DirectX 11 version will work fine, too.

ANGLE project is used by a lot of well known applications, including projects such as Chrome, Opera, and Firefox. It has a full compatibility with OpenGL ES 2.0.

**Comment by Anastaciaa** [comment] 2015-07-02 21:38
Ok wondering why Tibianic OTClient is running on OPENGL instead of dx9. Also would be great if you can do any tutorial about how to fix that ANGLE with otclient.

**Comment by iryont** [comment] 2015-07-03 10:15
Actually default engine is set to OpenGL, but you can find a DirectX 9.0c icon there, too. It uses ANGLE libraries which you can find there as well (libEGL.dll and libGLESv2.dll).

Also, unfortunately I cannot help you since I do use a different platform window creation mechanism than the one available in OTClient repository.

**Comment by likamawa** [comment] 2015-12-09 04:42
i believe you only have to set

OPENGL_ES=2.0

In the CMake console as per pointed in the walkthrough.
