### ISSUE TITLE
Map traversal (autowalk) bug -> infinite traversal loop

### ISSUE THREAD

**Issue by Source61** [edubart/otclient#1109] opened 2020-09-10 17:22 UTC
Found this bug on my 1 year old otclient.
Replicated the bug on the "latest" otclient, specifically commit 59059321a6276890e4a14841957f6838fab342f1.

The recording failed to capture the cursor despite being set to do so, in the recording I'm clicking the minimap once to the center south in between the large grey area on the right side and the small house area on the left side which is being traversed in the recording.
[https://s8.gifyu.com/images/ezgif.com-optimize06e7958970442f0d.gif](https://s8.gifyu.com/images/ezgif.com-optimize06e7958970442f0d.gif)

**Comment by Source61** [comment] 2021-02-18 12:06
Update: I've hired a developer that's fixed this bug and many many more (about 100 in total, half of them fixed by me over the past year).
I paid $35 for this fix + another pathing improvement and will release both for $35 if anyone's interested.
Proof: https://i.imgur.com/HI0eveN.gif

**Comment by diath** [comment] 2021-02-18 16:09
Duplicate of #840.

**Closed by diath** 2021-02-18 16:09 UTC
