### ISSUE TITLE
Tibia 8.60 Demon Oak

### ISSUE THREAD

**Issue by dev1lwalks** [edubart/otclient#763] opened 2016-10-09 19:02 UTC
Unable to use the axe on the left arm of the Demon Oak it didn't work in different servers then tried using the regular client and it worked any helps around here ? Didn't change anything but "gamelib/const.lua" and "/src/client/protocolcodes.cpp" the "messageModesMap[Otc::MessageNpcFromStartBlock] = 5;" line.

**Comment by Zbizu** [comment] 2016-12-14 07:38
This was fixed on server side
https://github.com/otland/forgottenserver/issues/1225

**Closed** 2016-12-14 11:08 UTC

**Comment by TheSumm** [comment] 2016-12-14 11:23
The issue is that getTopMultiUseThing retrieves the wrong item. This is not a server issue, but a client issue.

**Comment by Zbizu** [comment] 2016-12-18 13:32
duplicate with #644 anyway @TheSumm
